In [3]:
import pandas as pd
import os

In [29]:
!pwd
!ls -la

/home/anita/code/MadMax1995bb/powder_alert2.0/notebooks

total 50444
drwxr-xr-x 2 anita anita     4096 Dec 10 10:34 .
drwxr-xr-x 8 anita anita     4096 Dec 10 09:03 ..
-rw-r--r-- 1 anita anita 51576832 Dec  9 15:39 .cache.sqlite
-rw-r--r-- 1 anita anita        0 Dec  9 14:54 .keep
-rw-r--r-- 1 anita anita    59870 Dec  9 18:03 notebook_Anita-Gei_get_openmeteo_data.ipynb
-rw-r--r-- 1 anita anita     3165 Dec 10 10:49 notebook_Anita-Gei_model_tests.ipynb

In [39]:
current_dir = os.getcwd()
relative_path = os.path.dirname(current_dir)
file_name = "raw_data/historical_weather_openmeteo_01011979-08122024.csv"

file_path = os.path.join(relative_path, file_name)

try:
    df_hist_openmeteo = pd.read_csv(file_path)
    df_hist_openmeteo.head()
except FileNotFoundError:
    print(f"The file at {file_path} was not found.")

df_hist_openmeteo

,date,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,snow_depth,weather_code,...,wind_gusts_10m,soil_temperature_0_to_7cm,soil_temperature_7_to_28cm,soil_temperature_28_to_100cm,soil_temperature_100_to_255cm,soil_moisture_0_to_7cm,soil_moisture_7_to_28cm,soil_moisture_28_to_100cm,soil_moisture_100_to_255cm,sunshine_duration
0,1979-01-01 00:00:00+00:00,-5.499,92.659720,-6.499,-9.440102,0.1,0.1,0.00,0.47,51.0,...,42.120000,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0
1,1979-01-01 01:00:00+00:00,-5.349,94.816150,-6.049,-9.425217,0.2,0.1,0.07,0.47,71.0,...,46.079998,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0
2,1979-01-01 02:00:00+00:00,-5.449,95.538070,-6.049,-9.401998,0.5,0.1,0.28,0.47,73.0,...,48.600000,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0
3,1979-01-01 03:00:00+00:00,-5.249,94.100266,-6.049,-8.945052,0.5,0.1,0.28,0.47,73.0,...,48.239998,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0
4,1979-01-01 04:00:00+00:00,-4.149,89.288180,-5.649,-7.644061,0.4,0.0,0.28,0.48,73.0,...,35.280000,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402691,2024-12-08 19:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402692,2024-12-08 20:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402693,2024-12-08 21:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402694,2024-12-08 22:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402695,2024-12-08 23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df_hist_openmeteo['date'] = pd.to_datetime(df_hist_openmeteo['date'], infer_datetime_format=True)
#df_hist_openmeteo.set_index(['date'], inplace=True)
df_hist_openmeteo.head(3)

/tmp/ipykernel_31006/3342115671.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df_hist_openmeteo['date'] = pd.to_datetime(df_hist_openmeteo['date'], infer_datetime_format=True)

,date,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,snow_depth,weather_code,...,wind_gusts_10m,soil_temperature_0_to_7cm,soil_temperature_7_to_28cm,soil_temperature_28_to_100cm,soil_temperature_100_to_255cm,soil_moisture_0_to_7cm,soil_moisture_7_to_28cm,soil_moisture_28_to_100cm,soil_moisture_100_to_255cm,sunshine_duration
0,1979-01-01 00:00:00+00:00,-5.499,92.65972,-6.499,-9.440102,0.1,0.1,0.00,0.47,51.0,...,42.120000,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0
1,1979-01-01 01:00:00+00:00,-5.349,94.81615,-6.049,-9.425217,0.2,0.1,0.07,0.47,71.0,...,46.079998,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0
2,1979-01-01 02:00:00+00:00,-5.449,95.53807,-6.049,-9.401998,0.5,0.1,0.28,0.47,73.0,...,48.600000,-0.749,-0.649,0.301,2.201,0.316,0.315,0.304,0.367,0.0

In [41]:
df_hist_openmeteo.dtypes

date                             datetime64[ns, UTC]
temperature_2m                               float64
relative_humidity_2m                         float64
dew_point_2m                                 float64
apparent_temperature                         float64
precipitation                                float64
rain                                         float64
snowfall                                     float64
snow_depth                                   float64
weather_code                                 float64
pressure_msl                                 float64
surface_pressure                             float64
cloud_cover                                  float64
cloud_cover_low                              float64
cloud_cover_mid                              float64
cloud_cover_high                             float64
et0_fao_evapotranspiration                   float64
vapour_pressure_deficit                      float64
wind_speed_10m                               float64
wind_speed_100m                              float64
wind_direction_10m                           float64
wind_direction_100m                          float64
wind_gusts_10m                               float64
soil_temperature_0_to_7cm                    float64
soil_temperature_7_to_28cm                   float64
soil_temperature_28_to_100cm                 float64
soil_temperature_100_to_255cm                float64
soil_moisture_0_to_7cm                       float64
soil_moisture_7_to_28cm                      float64
soil_moisture_28_to_100cm                    float64
soil_moisture_100_to_255cm                   float64
sunshine_duration                            float64
dtype: object

In [46]:
from darts import TimeSeries

ModuleNotFoundError: No module named 'darts'

In [ ]:
series = TimeSeries.from_dataframe(df, "Month", "#Passengers")
df_hist_openmeteo.plot(x=df_hist_openmeteo['date'], y=df_hist_openmeteo['snowfall'])

KeyError: "None of [DatetimeIndex(['1979-01-01 00:00:00+00:00', '1979-01-01 01:00:00+00:00',\n               '1979-01-01 02:00:00+00:00', '1979-01-01 03:00:00+00:00',\n               '1979-01-01 04:00:00+00:00', '1979-01-01 05:00:00+00:00',\n               '1979-01-01 06:00:00+00:00', '1979-01-01 07:00:00+00:00',\n               '1979-01-01 08:00:00+00:00', '1979-01-01 09:00:00+00:00',\n               ...\n               '2024-12-08 14:00:00+00:00', '2024-12-08 15:00:00+00:00',\n               '2024-12-08 16:00:00+00:00', '2024-12-08 17:00:00+00:00',\n               '2024-12-08 18:00:00+00:00', '2024-12-08 19:00:00+00:00',\n               '2024-12-08 20:00:00+00:00', '2024-12-08 21:00:00+00:00',\n               '2024-12-08 22:00:00+00:00', '2024-12-08 23:00:00+00:00'],\n              dtype='datetime64[ns, UTC]', length=402696, freq=None)] are in the [columns]"

In [42]:
y = df_hist_openmeteo['snowfall']
X = df_hist_openmeteo.drop(columns='snowfall')